name: tiwentianbao1

on:
  workflow_dispatch: #在actions界面点击即可运行
  schedule:
    - cron: '10 3,4 * * *'  
  #Runs at 03:10 and 04:10 UTC every day.beijing + 8
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run:  pip install -r ./requests.txt  #此处为安装依赖包
    - run: python ./temperature.py  #此处为python代码的文件名
