name: tiwentianbao1

on:
  workflow_dispatch: #在actions界面点击即可运行
  schedule:
    - cron: '10 4,5 * * *'  
  #Runs at 04:10 and 05:10 UTC every day，也就是北京时间12点10分和13点10分
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run:  pip install -r ./requests.txt  #此处为安装依赖包
    - run: python ./temperature.py  #此处为python代码的文件名
